// Generated by the Supabase MCP `generate_typescript_types` for project
// cfxzvmtowcsevtnmyqeg (last synced with migration 0009 on 2026-09-18). Regenerate after every migration.
export type Json =
  | string
  | number
  | boolean
  | null
  | { [key: string]: Json | undefined }
  | Json[]

export type Database = {
  // Allows to automatically instantiate createClient with right options
  // instead of createClient<Database, { PostgrestVersion: 'XX' }>(URL, KEY)
  __InternalSupabase: {
    PostgrestVersion: '14.5'
  }
  public: {
    Tables: {
      bookings: {
        Row: {
          advance: number
          booking_date: string
          booking_no: string
          bus: string
          client_updated_at: number
          created_at: string
          created_by: string
          deleted_at: string | null
          departure_time: string
          device_id: string | null
          fare: number
          from_place: string
          id: string
          mobile: string
          name: string
          organization_id: string
          issued_by_name: string
          mobile2: string
          pad_color: string
          page: Json
          post: string
          return_date: string | null
          return_time: string
          seq: number | null
          share_pdf_path: string | null
          share_png_path: string | null
          share_rendered_at: number | null
          template: string
          thana: string
          to_place: string
          travel_date: string | null
          updated_at: string
          updated_by: string
          village: string
        }
        Insert: {
          advance?: number
          booking_date: string
          booking_no: string
          bus?: string
          client_updated_at: number
          created_at?: string
          created_by: string
          deleted_at?: string | null
          departure_time?: string
          device_id?: string | null
          fare?: number
          from_place?: string
          id: string
          mobile?: string
          name?: string
          organization_id: string
          issued_by_name?: string
          mobile2?: string
          pad_color?: string
          page?: Json
          post?: string
          return_date?: string | null
          return_time?: string
          seq?: number | null
          share_pdf_path?: string | null
          share_png_path?: string | null
          share_rendered_at?: number | null
          template: string
          thana?: string
          to_place?: string
          travel_date?: string | null
          updated_at?: string
          updated_by: string
          village?: string
        }
        Update: {
          advance?: number
          booking_date?: string
          booking_no?: string
          bus?: string
          client_updated_at?: number
          created_at?: string
          created_by?: string
          deleted_at?: string | null
          departure_time?: string
          device_id?: string | null
          fare?: number
          from_place?: string
          id?: string
          mobile?: string
          name?: string
          organization_id?: string
          issued_by_name?: string
          mobile2?: string
          pad_color?: string
          page?: Json
          post?: string
          return_date?: string | null
          return_time?: string
          seq?: number | null
          share_pdf_path?: string | null
          share_png_path?: string | null
          share_rendered_at?: number | null
          template?: string
          thana?: string
          to_place?: string
          travel_date?: string | null
          updated_at?: string
          updated_by?: string
          village?: string
        }
        Relationships: [
          {
            foreignKeyName: 'bookings_device_id_fkey'
            columns: ['device_id']
            isOneToOne: false
            referencedRelation: 'devices'
            referencedColumns: ['id']
          },
          {
            foreignKeyName: 'bookings_organization_id_fkey'
            columns: ['organization_id']
            isOneToOne: false
            referencedRelation: 'organizations'
            referencedColumns: ['id']
          },
        ]
      }
      devices: {
        Row: {
          code: string
          id: string
          last_seen_at: string
          name: string
          organization_id: string
          user_id: string
        }
        Insert: {
          code: string
          id: string
          last_seen_at?: string
          name?: string
          organization_id: string
          user_id: string
        }
        Update: {
          code?: string
          id?: string
          last_seen_at?: string
          name?: string
          organization_id?: string
          user_id?: string
        }
        Relationships: [
          {
            foreignKeyName: 'devices_organization_id_fkey'
            columns: ['organization_id']
            isOneToOne: false
            referencedRelation: 'organizations'
            referencedColumns: ['id']
          },
        ]
      }
      memberships: {
        Row: {
          created_at: string
          organization_id: string
          revoked_at: string | null
          role: Database['public']['Enums']['membership_role']
          user_id: string
        }
        Insert: {
          created_at?: string
          organization_id: string
          revoked_at?: string | null
          role?: Database['public']['Enums']['membership_role']
          user_id: string
        }
        Update: {
          created_at?: string
          organization_id?: string
          revoked_at?: string | null
          role?: Database['public']['Enums']['membership_role']
          user_id?: string
        }
        Relationships: [
          {
            foreignKeyName: 'memberships_organization_id_fkey'
            columns: ['organization_id']
            isOneToOne: false
            referencedRelation: 'organizations'
            referencedColumns: ['id']
          },
        ]
      }
      number_blocks: {
        Row: {
          device_id: string
          end_seq: number
          id: number
          organization_id: string
          reserved_at: string
          start_seq: number
        }
        Insert: {
          device_id: string
          end_seq: number
          id?: never
          organization_id: string
          reserved_at?: string
          start_seq: number
        }
        Update: {
          device_id?: string
          end_seq?: number
          id?: never
          organization_id?: string
          reserved_at?: string
          start_seq?: number
        }
        Relationships: [
          {
            foreignKeyName: 'number_blocks_device_id_fkey'
            columns: ['device_id']
            isOneToOne: false
            referencedRelation: 'devices'
            referencedColumns: ['id']
          },
          {
            foreignKeyName: 'number_blocks_organization_id_fkey'
            columns: ['organization_id']
            isOneToOne: false
            referencedRelation: 'organizations'
            referencedColumns: ['id']
          },
        ]
      }
      organization_counters: {
        Row: {
          next_seq: number
          organization_id: string
        }
        Insert: {
          next_seq?: number
          organization_id: string
        }
        Update: {
          next_seq?: number
          organization_id?: string
        }
        Relationships: [
          {
            foreignKeyName: 'organization_counters_organization_id_fkey'
            columns: ['organization_id']
            isOneToOne: true
            referencedRelation: 'organizations'
            referencedColumns: ['id']
          },
        ]
      }
      organizations: {
        Row: {
          created_at: string
          id: string
          name: string
        }
        Insert: {
          created_at?: string
          id?: string
          name: string
        }
        Update: {
          created_at?: string
          id?: string
          name?: string
        }
        Relationships: []
      }
      profiles: {
        Row: {
          created_at: string
          display_name: string
          email: string
          id: string
        }
        Insert: {
          created_at?: string
          display_name?: string
          email?: string
          id: string
        }
        Update: {
          created_at?: string
          display_name?: string
          email?: string
          id?: string
        }
        Relationships: []
      }
    }
    Views: {
      [_ in never]: never
    }
    Functions: {
      device_code_for: { Args: { n: number }; Returns: string }
      ensure_counter_at_least: { Args: { p_next: number }; Returns: undefined }
      is_member: { Args: { org: string }; Returns: boolean }
      is_member_of_text: { Args: { org: string }; Returns: boolean }
      is_owner: { Args: { org: string }; Returns: boolean }
      my_membership: {
        Args: never
        Returns: {
          display_name: string
          organization_id: string
          organization_name: string
          role: Database['public']['Enums']['membership_role']
        }[]
      }
      register_device: {
        Args: { p_device_id: string; p_name?: string }
        Returns: string
      }
      reserve_number_block: {
        Args: { p_device_id: string; p_size?: number }
        Returns: {
          end_seq: number
          start_seq: number
        }[]
      }
      update_member: {
        Args: {
          p_organization_id: string
          p_user_id: string
          p_display_name: string
          p_role: Database['public']['Enums']['membership_role']
        }
        Returns: undefined
      }
      shares_organization_with: { Args: { other: string }; Returns: boolean }
    }
    Enums: {
      membership_role: 'owner' | 'staff'
    }
    CompositeTypes: {
      [_ in never]: never
    }
  }
}

type DatabaseWithoutInternals = Omit<Database, '__InternalSupabase'>

type DefaultSchema = DatabaseWithoutInternals[Extract<keyof Database, 'public'>]

export type Tables<
  DefaultSchemaTableNameOrOptions extends
    | keyof (DefaultSchema['Tables'] & DefaultSchema['Views'])
    | { schema: keyof DatabaseWithoutInternals },
  TableName extends (DefaultSchemaTableNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof (DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions['schema']]['Tables'] &
        DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions['schema']]['Views'])
    : never) = never,
> = DefaultSchemaTableNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals
}
  ? (DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions['schema']]['Tables'] &
      DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions['schema']]['Views'])[TableName] extends {
      Row: infer R
    }
    ? R
    : never
  : DefaultSchemaTableNameOrOptions extends keyof (DefaultSchema['Tables'] & DefaultSchema['Views'])
    ? (DefaultSchema['Tables'] & DefaultSchema['Views'])[DefaultSchemaTableNameOrOptions] extends {
        Row: infer R
      }
      ? R
      : never
    : never

export type TablesInsert<
  DefaultSchemaTableNameOrOptions extends keyof DefaultSchema['Tables'] | { schema: keyof DatabaseWithoutInternals },
  TableName extends (DefaultSchemaTableNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions['schema']]['Tables']
    : never) = never,
> = DefaultSchemaTableNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals
}
  ? DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions['schema']]['Tables'][TableName] extends {
      Insert: infer I
    }
    ? I
    : never
  : DefaultSchemaTableNameOrOptions extends keyof DefaultSchema['Tables']
    ? DefaultSchema['Tables'][DefaultSchemaTableNameOrOptions] extends {
        Insert: infer I
      }
      ? I
      : never
    : never

export type TablesUpdate<
  DefaultSchemaTableNameOrOptions extends keyof DefaultSchema['Tables'] | { schema: keyof DatabaseWithoutInternals },
  TableName extends (DefaultSchemaTableNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions['schema']]['Tables']
    : never) = never,
> = DefaultSchemaTableNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals
}
  ? DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions['schema']]['Tables'][TableName] extends {
      Update: infer U
    }
    ? U
    : never
  : DefaultSchemaTableNameOrOptions extends keyof DefaultSchema['Tables']
    ? DefaultSchema['Tables'][DefaultSchemaTableNameOrOptions] extends {
        Update: infer U
      }
      ? U
      : never
    : never

export type Enums<
  DefaultSchemaEnumNameOrOptions extends keyof DefaultSchema['Enums'] | { schema: keyof DatabaseWithoutInternals },
  EnumName extends (DefaultSchemaEnumNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof DatabaseWithoutInternals[DefaultSchemaEnumNameOrOptions['schema']]['Enums']
    : never) = never,
> = DefaultSchemaEnumNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals
}
  ? DatabaseWithoutInternals[DefaultSchemaEnumNameOrOptions['schema']]['Enums'][EnumName]
  : DefaultSchemaEnumNameOrOptions extends keyof DefaultSchema['Enums']
    ? DefaultSchema['Enums'][DefaultSchemaEnumNameOrOptions]
    : never

export const Constants = {
  public: {
    Enums: {
      membership_role: ['owner', 'staff'],
    },
  },
} as const
